#==============================
# General site config
#==============================

title: Ilja Panic
author: Ilja Panic
email: ilja@iljapanic.com
description: Personal site of Ilja A. Panic
url: https://iljapanic.com
repo: https://github.com/iljapanic/iljapanic-com
timezone: Europe/Prague
ga: UA-43693985-11

twitter: https://twitter.com/iljapanic
linkedin: https://www.linkedin.com/in/iljapanic/
instagram: https://instagram.com/iljapanic/
github: https://github.com/iljapanic

#==============================
# Build config
#==============================

permalink: /blog/:year/:title/
markdown: kramdown

plugins:
  - jekyll-typogrify

gem:
  - jekyll-figure

#==============================
# Exclude/Include
#==============================
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - gulpfile.js/
  - yarn.lock
  - _assets/
  - _images/
  - _data/
  - _books
  - _temp/


#==============================
# custom collections
#==============================

# collections:
#   notes:
#     output: true
#     permalink: /notes/:year/:title/
#   links:
#     output: true
#     permalink: /links/:year/:title/
