[build]
  publish = "public/"
  command = "gatsby build"

[[redirects]]
  from = "/music"
  to = "/listen"

[[redirects]]
  from = "/articles"
  to = "/essays"

[[redirects]]
  from = "/articles/*"
  to = "/essays/:splat"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-sitemap"
