[build]
  publish = "public/"
  command = "gatsby build"

[dev]
  publish = "public/"
  command = "npm run serve"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-sitemap"
