[phases.setup]
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
  'bun install'
]

[phases.build]
cmds = [
  'bunx prisma generate',
  'bun run build'
]

[start]
cmd = 'sh -c "bunx prisma migrate deploy && bun start"'

[variables]
NODE_ENV = 'production'
